services:
    fedora-zendmm:
        image: dkarlovi/mimalloc-php:fedora-zendmm
        build:
            target: fedora-zendmm
    fedora-malloc:
        image: dkarlovi/mimalloc-php:fedora-malloc
        build:
            target: fedora-malloc
    fedora-mimalloc:
        image: dkarlovi/mimalloc-php:fedora-mimalloc
        build:
            target: fedora-mimalloc
    alpine-zendmm:
        image: dkarlovi/mimalloc-php:alpine-zendmm
        build:
            target: alpine-zendmm
    alpine-malloc:
        image: dkarlovi/mimalloc-php:alpine-malloc
        build:
            target: alpine-malloc
    alpine-mimalloc:
        image: dkarlovi/mimalloc-php:alpine-mimalloc
        build:
            target: alpine-mimalloc
    docker-debian-zendmm:
        image: dkarlovi/mimalloc-php:docker-debian-zendmm
        build:
            target: docker-debian-zendmm
    docker-debian-malloc:
        image: dkarlovi/mimalloc-php:docker-debian-malloc
        build:
            target: docker-debian-malloc
    docker-debian-mimalloc:
        image: dkarlovi/mimalloc-php:docker-debian-mimalloc
        build:
            target: docker-debian-mimalloc
    docker-alpine-zendmm:
        image: dkarlovi/mimalloc-php:docker-alpine-zendmm
        build:
            target: docker-alpine-zendmm
    docker-alpine-malloc:
        image: dkarlovi/mimalloc-php:docker-alpine-malloc
        build:
            target: docker-alpine-malloc
    docker-alpine-mimalloc:
        image: dkarlovi/mimalloc-php:docker-alpine-mimalloc
        build:
            target: docker-alpine-mimalloc
    wolfi-zendmm:
        image: dkarlovi/mimalloc-php:wolfi-zendmm
        build:
            target: wolfi-zendmm
    wolfi-malloc:
        image: dkarlovi/mimalloc-php:wolfi-malloc
        build:
            target: wolfi-malloc
