services:
    fedora-malloc:
        image: dkarlovi/mimalloc-php:fedora-malloc
        build:
            target: fedora-malloc
    alpine-malloc:
        image: dkarlovi/mimalloc-php:alpine-malloc
        build:
            target: alpine-malloc
    alpine-mimalloc2:
        image: dkarlovi/mimalloc-php:alpine-mimalloc2
        build:
            target: alpine-mimalloc2
